import type { Project } from "../types/data";
import { TECH } from "./technologies";

export const projects: Project[] = [
  {
    id: 1,
    image: "assets/projects/portfolio.png",
    tags: [TECH.REACT, TECH.TS, TECH.TAILWIND, TECH.FRAMER_MOTION],
    github: "https://github.com/DuyPhatpeo/portfolio",
    demo: "https://tranduyphat.vercel.app/",
    featured: true,
    reverse: false,
  },
  {
    id: 10,
    image: "assets/projects/linksnap.png",
    tags: [TECH.LARAVEL, TECH.PHP, TECH.HTML, TECH.CSS, TECH.JS, TECH.TAILWIND, TECH.MYSQL],
    github: "https://github.com/DuyPhatpeo/link-snap",
    demo: null,
    featured: true,
    reverse: true,
  },
  {
    id: 4,
    image: "assets/projects/weather-app.png",
    tags: [TECH.REACT, TECH.TS, TECH.TAILWIND, TECH.ZUSTAND],
    github: "https://github.com/DuyPhatpeo/weather-app",
    demo: "https://thoitiet24h.vercel.app/",
    featured: true,
    reverse: false,
  },

  // Other Projects
  {
    id: 2,
    image: "assets/projects/ecommerce.png",
    tags: [TECH.REACT, TECH.TS, TECH.TAILWIND, TECH.FIREBASE, TECH.ZUSTAND],
    github: "https://github.com/DuyPhatpeo/ecommerce",
    demo: "https://ecommerce-phat.vercel.app/",
    featured: false,
  },
  {
    id: 9,
    image: "assets/projects/pokedex.png",
    tags: [TECH.REACT_NATIVE, TECH.EXPO, TECH.TS, TECH.NATIVEWIND, TECH.ZUSTAND],
    github: "https://github.com/DuyPhatpeo/pokedex",
    demo: null,
    featured: false,
  },
  {
    id: 3,
    image: "assets/projects/restaurant.png",
    tags: [TECH.REACT, TECH.FIREBASE],
    github: "https://github.com/DuyPhatpeo/restaurant",
    demo: "https://restaurant-phat.vercel.app/",
    featured: false,
  },
  {
    id: 5,
    image: "assets/projects/dinomovie.png",
    tags: [TECH.REACT, TECH.TAILWIND],
    github: "https://github.com/DuyPhatpeo/simple-movies",
    demo: "https://dinomovie.vercel.app",
    featured: false,
  },
  {
    id: 6,
    image: "assets/projects/dinostore.jpg",
    tags: [TECH.REACT, TECH.TAILWIND],
    github: "https://github.com/DuyPhatpeo/dinostore",
    demo: "https://dinostorevn.vercel.app/",
    featured: false,
  },
  {
    id: 7,
    image: "assets/projects/dinobotweb.png",
    tags: [TECH.NODE_JS, TECH.DISCORD_JS],
    github: "https://github.com/DuyPhatpeo/DinoBotDiscord",
    demo: "https://dinobotvn.vercel.app/",
    featured: false,
  },
  {
    id: 8,
    image: "assets/projects/shopfstyle.jpg",
    tags: [TECH.PHP, TECH.HTML, TECH.CSS, TECH.JS, TECH.MYSQL, TECH.TAILWIND],
    github: "https://github.com/DuyPhatpeo/ShopFSTYLE",
    demo: null,
    featured: false,
  },
];
