import type { Project, Skill } from "../types/data";

export const projects: Project[] = [
  {
    id: 10,
    image: "assets/projects/linksnap.png",
    tags: ["Laravel", "PHP", "Tailwind CSS", "MySQL", "Vite"],
    github: "https://github.com/DuyPhatpeo/rutgonlink",
    demo: "https://linksnap.free.laravel.cloud/",
    featured: true,
    reverse: false,
  },
  {
    id: 1,
    image: "assets/projects/portfolio.png",
    tags: ["React", "TypeScript", "Vite", "Tailwind CSS", "Framer Motion"],
    github: "https://github.com/DuyPhatpeo/portfolio",
    demo: "https://tranduyphat.vercel.app/",
    featured: true,
    reverse: true,
  },
  {
    id: 4,
    image: "assets/projects/weather-app.png",
    tags: ["React 18", "TypeScript", "Tailwind CSS", "Zustand"],
    github: "https://github.com/DuyPhatpeo/weather-app",
    demo: "https://thoitiet24h.vercel.app/",
    featured: true,
    reverse: false,
  },

  // Other Projects
  {
    id: 2,
    image: "assets/projects/ecommerce.png",
    tags: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Firebase",
      "Zustand",
    ],
    github: "https://github.com/DuyPhatpeo/ecommerce",
    demo: "https://ecommerce-phat.vercel.app/",
    featured: false,
  },
  {
    id: 9,
    image: "assets/projects/pokedex.png",
    tags: ["React Native", "Expo", "TypeScript", "NativeWind", "Zustand"],
    github: "https://github.com/DuyPhatpeo/pokedex",
    demo: null,
    featured: false,
  },
  {
    id: 3,
    image: "assets/projects/restaurant.png",
    tags: ["React", "Vite", "Firebase", "Axios"],
    github: "https://github.com/DuyPhatpeo/restaurant",
    demo: "https://restaurant-phat.vercel.app/",
    featured: false,
  },
  {
    id: 5,
    image: "assets/projects/dinomovie.png",
    tags: ["React", "Vite", "Tailwind CSS", "Axios", "React Router"],
    github: "https://github.com/DuyPhatpeo/simple-movies",
    demo: "https://dinomovie.vercel.app",
    featured: false,
  },
  {
    id: 6,
    image: "assets/projects/dinostore.jpg",
    tags: ["React", "Vite", "Axios", "React Router"],
    github: "https://github.com/DuyPhatpeo/dinostore",
    demo: "https://dinostorevn.vercel.app/",
    featured: false,
  },
  {
    id: 7,
    image: "assets/projects/dinobotweb.png",
    tags: ["Node.js", "Discord.js"],
    github: "https://github.com/DuyPhatpeo/DinoBotDiscord",
    demo: "https://dinobotvn.vercel.app/",
    featured: false,
  },
  {
    id: 8,
    image: "assets/projects/shopfstyle.jpg",
    tags: ["PHP", "MySQL", "Tailwind CSS", "JavaScript"],
    github: "https://github.com/DuyPhatpeo/ShopFSTYLE",
    demo: "",
    featured: false,
  },
];
